ImageGallery/Models/GalleryImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ImageGallery.Models
{
    public class GalleryImage
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ThumbnailFileName { get; set; }
        public string FileName { get; set; }
    }
}

ImageGallery/Models/ViewModels/ImageUploadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ImageGallery.Models.ViewModels
{
    public class ImageUploadViewModel
    {
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

ImageGallery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageGallery.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ImageGallery/Controllers/ImageController.cs
using ImageGallery.Data;
using ImageGallery.Models;
using ImageGallery.Models.ViewModels;
using ImageMagick;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ImageGallery.Controllers
{
    public class ImageController : Controller
    {
        private ImageGalleryDbContext db = new ImageGalleryDbContext();
        private Random random = new Random();

        // GET: Image
        public ActionResult Index()
        {
            var images = db.Images.ToList();
            ViewBag.Images = images;
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(ImageUploadViewModel model)
        {
            var fileNames = SaveImage(model.ImageFile);

            var image = new GalleryImage
            {
                Title = model.Title,
                Description = model.Description,
                ThumbnailFileName = fileNames.thumbFileName,
                FileName = fileNames.fileName
            };

            db.Images.Add(image);
            await db.SaveChangesAsync();

            return Redirect("/Image");
        }

        // GET: Image/Details/5
        public ActionResult Details(int id)
        {
            var imageDetails = db.Images.Find(id);
            ViewBag.Image = imageDetails;
            return View();
        }

        // GET: Image/Delete/5
        public ActionResult Delete(int id)
        {
            var image = db.Images.Find(id);
            if (image != null)
            {
                var path = Server.MapPath("/Content/Images");
                var thumbPath = Path.Combine(path, image.ThumbnailFileName);
                var imagePath = Path.Combine(path, image.FileName);

                if (System.IO.File.Exists(thumbPath))
                {
                    System.IO.File.Delete(thumbPath);
                }

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }

                db.Images.Remove(image);
                db.SaveChanges();   
            }

            return RedirectToAction("Index");
        }

        private (string thumbFileName, string fileName) SaveImage(HttpPostedFileBase imageData)
        {
            var path = Server.MapPath("/Content/Images");
            Directory.CreateDirectory(path);
            var fileName = RandomString(10);

            using (MagickImage image = new MagickImage(imageData.InputStream))
            {
                var thumbnail = image.Clone();
                var desiredWidth = 320;
                var thumbnailRatio = thumbnail.Width / desiredWidth;
                var thumbnailWidth = thumbnail.Width / thumbnailRatio;
                var thumbnailHeight = thumbnail.Height / thumbnailRatio;
                thumbnail.Resize(thumbnailWidth, thumbnailHeight);
                var thumbnailFileName = $"{fileName}_thumb.jpg";
                var thumbnailFilePath = Path.Combine(path, thumbnailFileName);
                //thumbnail.Orientation = OrientationType.Undefined;
                thumbnail.Write(thumbnailFilePath);

                var fullFileName = $"{fileName}.jpg";
                var fullFilePath = Path.Combine(path, fullFileName);
                //image.Orientation = OrientationType.Undefined;
                image.Write(fullFilePath);

                return (thumbnailFileName, fullFileName);
            }
        }

        // from https://stackoverflow.com/questions/1344221
        public string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

ImageGallery/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ImageGallery/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ImageGallery/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ImageGallery/Views/Image/Add.cshtml
@{
    ViewBag.Title = "Add Image";
}

<h2>Add Image</h2>

<form action="/Image/Add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="Title">Image Title</label>
        <input class="form-control" type="text" name="Title" />
    </div>
    <div class="form-group">
        <label for="Description">Image Description</label>
        <input class="form-control" type="text" name="Description" />
    </div>
    <div class="form-group">
        <label for="ImageFile">Choose Image:</label>
        <input type="file" name="ImageFile" />
    </div>
    <br />
    <button class="btn btn-primary" type="submit">Add Image</button>
</form>

ImageGallery/Views/Image/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<style>
    img {
        image-orientation: from-image;
        width: 100%;
    }
</style>

<h2>Image Details</h2>

<div class="row">
    <h3>@ViewBag.Image.Title</h3>

    <img src="~/Content/Images/@ViewBag.Image.FileName" />
</div>
<br />
<div class="row">
    @ViewBag.Image.Description
</div>
<br />
<div class="row">
    <a class="btn btn-primary" href="/Image">Back To Gallery</a>
    <a class="btn btn-danger" href="/Image/Delete/@ViewBag.Image.Id">Delete Image</a>
</div>

ImageGallery/Views/Image/Index.cshtml
@{
    ViewBag.Title = "Images";
}

<h2>Images</h2>

<style>
    img {
        image-orientation: from-image;
    }

    .gallery-image {
        display: inline-block;
        width: 350px;
    }

    .buttons {
        margin-top: 50px;
    }
</style>

@foreach (var image in ViewBag.Images)
{
    var imageSrc = image.ThumbnailFileName;
    <div class="gallery-image">
        <h4>@image.Title</h4>
        <a href="/Image/Details/@image.Id">
            <img src="~/Content/Images/@imageSrc" />
        </a>
        <div>@image.Description</div>
    </div>
}

    <div class="row buttons">
        <a href="/Image/Add" class="btn btn-primary">Add Image</a>
    </div>

ImageGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Image Gallery</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Image Gallery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Gallery", "Index", "Image")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Image Gallery</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>